MODEL:
  ARCH: "Unet"
  ENCODER: "xception"
  ENCODER_WEIGHTS: "imagenet"
  NUM_CLASSES: 1
  MODE: "binary"
  ACT_FUNC: "sigmoid"
DATA:
  NAME: "retinal-lesions"
  DATA_ROOT: "./data/retinal-lesions-v20191227"
  RESIZE: [512,512]
  LABEL_VALUES: [127, 255]
  BINARY: True
  NUM_WORKERS: 8
LOSS:
  NAME: "CE+L1"
  ALPHA: 0.01
  ALPHA_FACTOR: 5
  ALPHA_STEP_SIZE: 10
  TEMP: 20.0
SOLVER:
  OPTIMIZING_METHOD: "adam"
  BASE_LR: 0.0001
  MOMENTUM: 0.9
  MAX_EPOCH: 50
  # LR_POLICY: "poly"
  LR_POLICY: "reduce_on_plateau"
  REDUCE_MODE: "min"
  FACTOR: 0.5
  PATIENCE: 6
TRAIN:
  DATA_PATH: "train_mul.txt"
  BATCH_SIZE: 8
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 5
  CALCULATE_METRIC: True
  # AUTO_RESUME: True
VAL:
  DATA_PATH: "val_mul.txt"
  BATCH_SIZE: 8
TEST:
  DATA_PATH: "test_mul.txt"
  BATCH_SIZE: 8
  CHECKPOINT_PATH: ""
TENSORBOARD:
  ENABLE: False
NEPTUNE:
  ENABLE: True
OUTPUT_DIR: ./log/retinal-lesions/retinal-lesions_r50fpn_bce_l1_sgd
RNG_SEED: 2
LOG_PERIOD: 30
DEVICE: "cuda:1"
PERFORM_TEST: True
